from __future__ import annotations

import os
import time
from pathlib import Path

import streamlit as st
from streamlit.components.v1 import html


HERE = Path(__file__).resolve().parent
DEFAULT_HTML_PATH = HERE / "output" / "dashboard_multi_year.html"


def load_dashboard_html(html_path: Path) -> str:
    """
    Load the static Plotly dashboard HTML file.

    Raises:
        FileNotFoundError: If the HTML file does not exist.
    """
    if not html_path.exists():
        raise FileNotFoundError(
            f"Dashboard HTML not found at {html_path}. "
            "Run `python Baltimore_MetricsWithMap.py` to regenerate it."
        )

    return html_path.read_text(encoding="utf-8")


def main() -> None:
    st.set_page_config(
        page_title="Baltimore Health Dashboard",
        page_icon="🗺️",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    st.title("🗺️ Baltimore City Health Dashboard")
    st.caption(
        "Streamlit wrapper for the interactive Plotly dashboard generated by "
        "`Baltimore_MetricsWithMap.py`."
    )

    st.sidebar.header("Dashboard Controls")
    html_path_str = st.sidebar.text_input(
        "Dashboard HTML Path",
        value=str(DEFAULT_HTML_PATH),
        help="Absolute path to the generated dashboard HTML file.",
    )
    html_path = Path(html_path_str).expanduser().resolve()

    auto_refresh = st.sidebar.checkbox("Auto-refresh", value=False)
    refresh_interval = st.sidebar.slider(
        "Refresh interval (seconds)",
        min_value=5,
        max_value=60,
        value=15,
        disabled=not auto_refresh,
    )

    refresh_button = st.sidebar.button("Reload Dashboard")

    if st.sidebar.button("Regenerate Instructions"):
        st.sidebar.info(
            "To rebuild the dashboard HTML, run:\n\n"
            "```bash\npython Baltimore_MetricsWithMap.py\n```"
        )

    # Simple auto-refresh mechanism
    if auto_refresh:
        placeholder = st.empty()
        refresh_countdown = refresh_interval
        placeholder.caption(f"Auto-refreshing in {refresh_countdown} seconds...")
        time.sleep(1)
        for remaining in range(refresh_interval - 1, -1, -1):
            placeholder.caption(f"Auto-refreshing in {remaining} seconds...")
            time.sleep(1)
        placeholder.empty()
        refresh_button = True

    # Load and display dashboard
    try:
        dashboard_html = load_dashboard_html(html_path)
        if refresh_button:
            st.success(f"Dashboard reloaded from {html_path}")

        html(
            dashboard_html,
            height=900,
            scrolling=True,
        )
    except FileNotFoundError as exc:
        st.error(str(exc))
        st.stop()
    except Exception as exc:
        st.error(f"Failed to load dashboard HTML: {exc}")
        st.stop()


if __name__ == "__main__":
    main()

